### ISSUE TITLE
The reconstructed object surface is not smooth

### ISSUE THREAD

**Issue by zhj296409022** [yanivw12/gs2mesh#2]
![0001](https://github.com/user-attachments/assets/87e32eed-2ee5-46fd-985d-92c8bb339873)

![image](https://github.com/user-attachments/assets/65714614-5d59-4d5b-97c6-7272d6c549b2)

Can you give me some advice

**Comment by yanivw12** [comment]
Did you change any of the default args? can you add  a print(args) between line 188 and 189 and take a screenshot of the output?
<img width="383" alt="image" src="https://github.com/user-attachments/assets/480d8b84-b274-44f3-b8b9-a24c0aeac810">

**Comment by zhj296409022** [comment]
The picture above is the result of training with 7000 iterations, I retrained it with 30,000 iterations.
![image](https://github.com/user-attachments/assets/816ec768-2d0a-45c3-92d3-1bea153536bd)

![image](https://github.com/user-attachments/assets/0005b7d2-412c-4a05-922f-a3e6a9f46a7f)

**Comment by yanivw12** [comment]
Try increasing the baseline of the stereo (and change the TSDF_min/max_depth_baselines accordingly - if you increase the baseline, you need to reduce these values so that you don't include background objects and result in a huge file size). I tried it with a printer I had, and got the following results:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/6262b0f2-fa77-4e21-ada8-d18aa23d7872">

With 7% baseline (TSDF between 4 and 20):
<img width="671" alt="image" src="https://github.com/user-attachments/assets/bc51e6fb-68be-45f8-b6f7-e5d03d488a39">

With 12% baseline (TSDF between 3 and 11):
<img width="719" alt="image" src="https://github.com/user-attachments/assets/15249534-89b6-4bf0-8a4b-e2206aba81ea">

In general, there will still be issues with textureless areas since stereo models tend to struggle with them. I have an idea that I'm testing to improve their performance, I will update if it helps. Additionally, I will add support for more robust GS models that should improve reconstruction quality as well.

From my experience, filming in landscape and getting closer with the camera for a cycle around the object can help produce better reconstructions, especially with larger objects (do 2 cycles, one from object height and one that's closer from slightly above the object).

**Comment by zhj296409022** [comment]
OK,Thank you for your advice.

**Comment by yanivw12** [comment]
I wanted to add a note on this matter:

Setting the stereo_warm to False (by inputting the no-stereo_warm paramater) helps with smoothness:

![image](https://github.com/user-attachments/assets/33367d77-20cd-4db1-b80b-531381ce9017)
