### ISSUE TITLE
How can I see the .ply in the output?

### ISSUE THREAD

**Issue by shichao1232** [yanivw12/gs2mesh#4]
![截图 2024-08-14 11-15-36](https://github.com/user-attachments/assets/a5bb4fa8-6f7f-4dc4-ab90-ffa03c3efaa4)
i use the meshlab to check my out ,but it was very bad ,I wonder what this json file does? How should I view the results correctly?

**Comment by yanivw12** [comment]
You don't need the json file to view the results, just open the .ply in meshlab. According to what I see, you only used 17 frames, which means you probably set video_interval to 50, which is about 1 frame every 2 seconds instead of the recommended 3fps (video_interval of 10 in this case). The sculpture video I uploaded was already downsampled to save space, and using only 17 images for the COLMAP+GS will result in poor splatting, from which it is not possible to extract a good mesh (I tried running it myself, and COLMAP can't create a sparse model with this frame rate, resulting in poor GS and poor reconstruction). I will add support for additional splatting methods that deal with sparse data better, but in the meantime, please use the recommended frame rate.

**Comment by shichao1232** [comment]
thanks，I have solved this problem

**Comment by yanivw12** [comment]
Good to hear! Also, note that in the updated repository from 2 days ago I uploaded a higher resolution video of the sculpture (1920x1080 instead of 1280x720) which further improves the reconstruction quality. I'm closing the issue for now.
