### ISSUE TITLE
Bad results for custom dataset

### ISSUE THREAD

**Issue by Alpgirl** [yanivw12/gs2mesh#5]
Good day!
I tried to launch GS2Mesh on Skoltech3D dataset (https://skoltech3d.appliedai.tech/). As an input, I leveraged COLMAP data (I computed SFM with known camera parameters). I followed the guide, which you specified in README, but my results are quite bad (I attached the scene and resulting mesh as files). What can be the reason?

Note: I also launched on MipNerf360 dataset, results were fine. 

<img width="940" alt="Снимок экрана 2024-08-20 в 23 41 46" src="https://github.com/user-attachments/assets/997bbe4f-2c37-45a7-a8fe-18f1559ff52d">
<img width="940" alt="Снимок экрана 2024-08-20 в 23 41 46" src="https://github.com/user-attachments/assets/1fbc0ba3-2116-4c9a-8457-7ca52225135b">

**Comment by yanivw12** [comment]
Hi,
After some struggling with downloading the relevant part of the dataset, I managed to download the specific scan of the box and play around with it. I got a pretty good reconstruction:

![image](https://github.com/user-attachments/assets/5618a277-dc25-4b5a-8ff2-68e83477b48b)

The thing is, the default arguments for the "custom" dataset, in which you added the scan, are suited for an "in the wild" 360 scan of an object. This dataset is more like DTU, as can be seen in the camera poses:

![image](https://github.com/user-attachments/assets/a3f98890-7eae-42d8-9c5e-d478ce09a62c)

This means that the baseline for stereo should be 14% and not 7% as it is by default (it has to do with how the baseline is being calculated using the camera locations, which assumes they are 360). The reason your mesh is blank is because the TSDF_max_depth_baselines parameter was half of what it should have been given the smaller baseline. Also, the scale of the COLMAP poses requires to set TSDF_scale to 0.1.
Also, setting stereo_warm to False helps for a smoother result.

To summarize, run the following command, assuming you have your COLMAP dataset already:

python run_single.py --colmap_name grey_braided_box --renderer_baseline_percentage 14 --TSDF_max_depth_baselines 30 --TSDF_scale 0.1 --no-stereo_warm --skip_video_extraction --skip_colmap

In general, when running the code for the first time on custom data, it's best to run via the interactive notebook, in order to visualize the intermediate steps and verify that they work correctly, and tune the various parameters (and you can even segment the object from the background like I did). 

Anyways, it's a pretty cool dataset that I didn't know existed - I might add official support for benchmarking on this dataset in the future, once they release the evaluation code (and maybe add a way to download just one set of images per scan instead of a 6GB zip file per scan...)

**Comment by yanivw12** [comment]
By the way, when I ran the code with the pre-computed COLMAP cameras and poses that were supplied, I noticed a bug in my renderer class initialization that assumed the camera numbers in cameras.txt start from 1. I fixed it now and updated the repository.

**Comment by Alpgirl** [comment]
Yes, I noticed it. Thanks for fixing!
As for the respond above, thank you for the detailed explanation! I am running the code. So, I will tell you about results soon.

**Comment by yanivw12** [comment]
One more thing to note, is that GS converts the background into noisy Gaussians:
![image](https://github.com/user-attachments/assets/d8908aa3-7f77-4f60-888a-dc796989f5f2)

As a result, the stereo will extract a mesh for these gaussians, turning the resulting mesh into a huge file. That's why I recommend using the interactive notebook for segmentation and background removal before inputting to TSDF. That's how you'll get the nice, clean mesh that I sent in an earlier message.

I will add support for automatic background removal soon, and then you won't even need the interactive notebook.

**Comment by Alpgirl** [comment]
I see. What do you mean by "interactive notebook"?

**Comment by yanivw12** [comment]
![image](https://github.com/user-attachments/assets/5493daed-3e04-4a5d-a406-e4ac3f28970f)

The file "custom_data.ipynb". Just make sure to edit the parameters at the beginning of the notebook according to what I sent earlier:
args.colmap_name = 'grey_braided_box'
args.renderer_baseline_percentage = 14 
args.TSDF_max_depth_baselines = 30 
args.TSDF_scale = 0.1 
args.stereo_warm = False
args.skip_video_extraction = True
args.skip_colmap = True

**Comment by Alpgirl** [comment]
Got it, thank you!

**Comment by Alpgirl** [comment]
The results for grey_braided_box are also good.
However, I noticed that for the scene "orange_mini_vacuum" the method is struggled to reconstruct opaque parts.
![IMG_20240822_130324_244](https://github.com/user-attachments/assets/ec058b6a-bf21-468a-8f3b-0158fc1200ea)

**Comment by yanivw12** [comment]
> The results for grey_braided_box are also good. However, I noticed that for the scene "orange_mini_vacuum" the method is struggled to reconstruct opaque parts.

Glad to hear that you've managed to get good results!

As you pointed out correctly, it is a known limitation of stereo matching models - they struggle to find correspondences on transparent surfaces. Other SOTA Gaussian Splatting-based surface reconstruction methods are also not that great with transparent surfaces. It is a known weakness in most surface reconstruction frameworks.

This is still an open area for research, and we are working towards more robust solutions.

**Comment by Alpgirl** [comment]
I see, thank you for the comment.

**Comment by yanivw12** [comment]
Is there anything else regarding this issue, or can it be closed?

**Comment by Alpgirl** [comment]
Can be closed, thank you!

**Comment by yanivw12** [comment]
Update: I just released an update with better support for non-360 scenes, and automatic masking in the script using GroundingDINO. See the main README for more details.

**Comment by Alpgirl** [comment]
Thank you for update!
